name: Unittests
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3
      - name: Run unittests
        run: python3 -m unittest discover -s tests -p "*_test.py"
